id: P009645
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-19 20:42:34.837653
source_metadata:
  id: bdr:W20520
  title: སྤོ་བོའི་ལོ་རྒྱུས
  author: ''
  volumes:
    9d6cb6d4aab34c4e811834b32b8bcfb7:
      image_group_id: I00KG06690
      title: ''
      volume_number: 1
      total_pages: 117
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
