id: IDE7A82F7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T18:57:22+00:00'
last_modified: '2022-06-08T12:32:13.271232+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20520
  title: སྤོ་བོའི་ལོ་རྒྱུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B41A:
      image_group_id: I00KG06690
      title: ''
      total_pages: 117
      order: 1
      base_file: B41A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
